name: Serverless CICD
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Install ESP-IDF and Build project
        uses: rmshub/esp-idf-action@v5
        with:
          esp_idf_version: v5.1.2
          esp_idf_target: esp32
